// data.js
const allDataPools = {
    "palavras": [
        ["A", "E"],
        ["A", "I"],
        ["Air", "R"],
        ["Ape", "Apple"],
        ["Apple", "Able"],
        ["Are", "Air"],
        ["Australia", "Austria"],
        ["Author", "Other"],

        ["Bat", "Beat"],
        ["Beach", "Bead"],
        ["Beach", "Beat"],
        ["Bed", "Bead"],
        ["Bee", "By"],
        ["Beer", "Bear"],
        ["Best", "Beast"],
        ["Bird", "Beard"],
        ["Bot", "Botch"],
        ["Breath", "Bread"],

        ["C", "Z"],
        ["Cable", "Able"],
        ["Calm", "Come"],
        ["Catch", "Cat"],
        ["Choose", "Chose"],
        ["Clearly", "Clear"],
        ["Cloth", "Clod"],
        ["Cold", "Call"],
        ["Cone", "Come"],
        ["Course", "Curse"],
        ["Curse", "Coarse"],

        ["D", "G"],
        ["Danger", "Dagger"],
        ["Deal", "Dial"],
        ["Door", "Poor"],
        ["Dope", "Dose"],
        ["Draw", "Drought"],
        ["Daughter", "Laughter"],

        ["E", "I"],
        ["Earth", "Earn"],
        ["Easy", "Ease"],
        ["Eighteen", "Eighteenth"],
        ["Eighteen", "Eightieth"],
        ["Eighty", "Eighth"],
        ["Eighty", "Eightieth"],
        ["Eighty", "Eighteen"],
        ["Evening", "Even"],
        ["Eve", "Even"],

        ["Fair", "Fear"],
        ["Fast", "Feast"],
        ["Fate", "Faith"],
        ["Fat", "Fetch"],
        ["Fifteen", "Fifteenth"],
        ["Fifteen", "Fiftieth"],
        ["Fifty", "Fifth"],
        ["Fifty", "Fiftieth"],
        ["Fifty", "Fifteen"],
        ["Fine", "Fin"],
        ["Fire", "Fear"],
        ["Fit", "Fight"],
        ["Fit", "Fish"],
        ["Fist", "Fish"],
        ["First", "Fist"],
        ["Flea", "Fly"],
        ["Flour", "Floor"],
        ["Fort", "Forty"],
        ["Forty", "Dirty"],
        ["Forty", "Fort"],
        ["Forty", "Fourth"],
        ["Forty", "Fortieth"],
        ["Forty", "Fourteen"],
        ["Four", "Fort"],
        ["Fourteen", "Fourteenth"],
        ["Fourteen", "Fortieth"],
        ["Fought", "Thought"],
        ["Full", "Fool"],
        ["Free", "Three"],

        ["Good", "God"],

        ["H", "8"],
        ["Hatch", "Hat"],
        ["Heal", "Real"],
        ["Healthy", "Help"],
        ["Hear", "Rear"],
        ["Heart", "Hard"],
        ["Here", "Hare"],
        ["Here", "Hire"],
        ["Hid", "Rid"],
        ["Him", "Rim"],
        ["Hip", "Rip"],
        ["Host", "Roast"],
        ["Hot", "Rot"],
        ["Hose", "House"],

        ["I", "Y"],
        ["It", "Its"],

        ["J", "G"],

        ["K", "Key"],
        ["K", "Q"],
        ["Key", "Q"],

        ["Let", "Latch"],
        ["Like", "Lick"],
        ["Loosen", "Loose"],
        ["Lose", "Lousy"],
        ["Lost", "Last"],

        ["Mad", "Made"],
        ["Mat", "Mash"],
        ["Mat", "Match"],
        ["Met", "Meat"],
        ["Month", "Mund"],
        ["Month", "Mouth"],
        ["Mutt", "Much"],

        ["Nine", "Ninth"],
        ["Nineteen", "Nineteenth"],
        ["Nineteen", "Ninetieth"],
        ["Ninety", "Ninth"],
        ["Ninety", "Nineteen"],
        ["Ninety", "Ninetieth"],
        ["North", "Nod"],

        ["One", "Want"],
        ["Oat", "Out"],
        ["Omen", "Woman"],
        ["Over", "Hover"],
        ["Out", "Gout"],
        ["Optimism", "Optimist"],

        ["Passion", "Pension"],
        ["Path", "Bath"],
        ["Path", "Past"],
        ["Path", "Patch"],
        ["Path", "Pat"],
        ["Pet", "Patch"],
        ["Pie", "Pea"],
        ["Pill", "Pile"],
        ["Pine", "Pin"],
        ["Post", "Pose"],
        ["Praise", "Price"],
        ["Put", "Pot"],

        ["Queue", "Key"],
        ["Question", "Quest"],
        ["Question", "Questioned"],

        ["Rail", "Real"],
        ["Rat", "Hat"],
        ["Rare", "Hare"],
        ["Rally", "Really"],
        ["Really", "Rely"],
        ["Reel", "Heel"],
        ["Reel", "Heal"],
        ["Repeat", "Repeated"],
        ["Rest", "Rested"],
        ["Roll", "Rolled"],
        ["Rich", "Reach"],
        ["Rit", "Hit"],
        ["Rit", "Rich"],
        ["Right", "White"],

        ["S", "Z"],
        ["School", "Skull"],
        ["Science", "Since"],
        ["Seventeen", "Seventeenth"],
        ["Seventeen", "Seventieth"],
        ["Seventy", "Seventeen"],
        ["Seventy", "Seventh"],
        ["Seventy", "Seventieth"],
        ["Ship", "Sheep"],
        ["Shore", "Chore"],
        ["Shoes", "Choose"],
        ["Simple", "Simply"],
        ["Sir", "Sure"],
        ["Sixty", "Sixteen"],
        ["Sixty", "Sixth"],
        ["Sixty", "Sixtieth"],
        ["Sixteen", "Sixteenth"],
        ["Sixteen", "Sixtieth"],
        ["Sleep", "Slip"],
        ["Sleep", "Split"],
        ["Sleep", "Spill"],
        ["Spill", "Spell"],
        ["Soon", "Son"],
        ["Sorely", "Solely"],
        ["Sorely", "Surely"],
        ["Sorry", "Sorely"],
        ["Space", "Spice"],
        ["Stop", "Spot"],
        ["Strip", "Stripe"],
        ["Sun", "Soon"],
        ["Sure", "Shore"],
        ["Sure", "Surely"],

        ["Ten", "Teen"],
        ["Ten", "Tenth"],
        ["Tense", "Tenth"],
        ["Teeth", "Tease"],
        ["Teeth", "Tenth"],
        ["Then", "Ten"],
        ["They", "Day"],
        ["They", "Their"],
        ["Third", "Thirst"],
        ["Thirty", "Dirty"],
        ["Thirty", "Third"],
        ["Thirty", "Thirteen"],
        ["Thirty", "Thirteenth"],
        ["Thirty", "Thirtieth"],
        ["Thirty", "Thirsty"],
        ["Thirteen", "Thirteenth"],
        ["Thirteenth", "Thirtieth"],
        ["Think", "Sink"],
        ["Thick", "Sick"],
        ["Though", "Tough"],
        ["Though", "Thought"],
        ["Thought", "Taught"],
        ["Throne", "Drone"],
        ["Throne", "Frawn"],
        ["Thrust", "Trust"],
        ["Thunder", "Under"],
        ["Tree", "Three"],
        ["Tree", "Try"],
        ["Tried", "Tired"],
        ["Tough", "Thought"],
        ["Twenty", "Twentieth"],
        ["Twelve", "Twenty"],
        ["Twelve", "Twelfth"],

        ["U", "Y"],
        ["United", "Unity"],
        ["Unit", "United"],
        ["Unit", "Unity"],

        ["Wait", "White"],
        ["Waste", "West"],
        ["Weld", "Wild"],
        ["Wild", "Wield"],
        ["Will", "Well"],
        ["Win", "When"],
        ["Wine", "Win"],
        ["Within", "Without"],
        ["Withhold", "Withdraw"],
        ["Withhold", "Without"],
        ["Without", "Withdraw"],
        ["World", "Word"],
        ["Worth", "Word"],
        ["Year", "Yearn"]

    ],
    "curtas": [
        ["I am here.", "I can't hear."],
        ["I can drive.", "I can dive."],
        ["He was home.", "We are home."],
        ["All of you.", "I love you."],
        ["Is it true?", "It is true."],
        ["How are you doing?", "What are you doing?"],
        ["They are people.", "There are people."],
        ["I love it.", "All of it."],
        ["Everybody's here.", "Everybody hears."],
        ["Can you see?", "Can't you see?"],
        ["They are people.", "There are people."],
        ["These are books", "They are books"],
        ["Are you ready?", "Are you reading?"],
        ["What did you say?", "Where did you stay?"],
        ["It's too cold.", "It isn't cold."],
        ["What did you say?", "What do you say?"],
        ["Why is that?", "What is that?"],
        ["This isn't right.", "This wasn't right."],
        ["Where are you going?", "When are you going?"],
        ["Is it clear?", "Is it near?"],
        ["That's not fair.", "That's not far."],
        ["It's close.", "It's closed."],
        ["Not too much.", "Not so much."],
        ["This is awesome.", "This is wholesome."],
        ["This is awful.", "This is awesome."],
        ["This is terrible.", "This is terrific."],
        ["This is great.", "This was great."],
        ["He's on the corner.", "He's in the corner."],
        ["I'm tired.", "I tried."],
        ["We're artists.", "Weird artists."],
        ["I have the keys.", "I have the case."],
        ["Good to see you!", "So good to see you!"],
        ["What's the problem?", "Where's the problem?"],
        ["It's right.", "It's night."],
        ["I study.", "I studied."],
        ["We talk.", "We talked."],
        ["They fail.", "They failed."],
        ["It's sunny.", "It's not sunny."],
        ["Today is Thursday.", "Today is Tuesday."],
        ["Today is Sunday.", "Today is Monday."],
        ["Today is Saturday.", "Today is Sunday."],
        ["Today is Friday.", "Today is Sunday."],
        ["It's June.", "It's July."],
        ["It's September.", "It's November."],
        ["It's December.", "It's September."],
        ["Today is the twentieth.", "Today is the twelfth."],
        ["Today is the first.", "Today is the third."],
        ["Today is the fifth.", "Today is the sixth."],
        ["Why so serious?", "Are you serious?"],
        ["This is what it is.", "I don't know what it is."],
        ["They will never forget.", "They will never forgive."],
        ["This is difficult.", "This is different."],
        ["Have a good day.", "Have a great day."],
        ["I hope you're doing well.", "I hope you're all doing well."],
        ["Nice to see you!", "Nice to meet you!"],
        ["Have a great week.", "Have a great weekend."],
        ["Where do you live?", "Who do you live with?"],
        ["This wasn't the plan.", "This was the plan."],
        ["Are you from Brazil?", "Are you in Brazil?"],
        ["Does he live with you?", "Does he talk to you?"],
        ["Did you get it?", "Did you see it?"],
        ["Why are we doing this?", "How are we doing this?"],
        ["You're such a funny person.", "You're such a fun person."],
        ["Are you okay?", "Are you alright?"],
        ["Do you know me?", "Do you know them?"],        
        ["I miss you.", "I'm seeing you."],
        ["No idea.", "Not ideal."],
        ["I knew it.", "I'm new to it."],
        ["What do you say?", "Why do you stay?"],
        ["I read the book.", "The book is red."],
        ["I know you.", "I'm not you."],
        ["How do you do?", "What do you do?"],
        ["I know you.", "I'm not you."],
        ["I'm hearing things.", "I'm doing things."],
        ["I'm hearing them.", "I'm here with them."],
        ["I am sleepy.", "I am sleeping."],
        ["It seems right.", "It isn't right."],

        ["The ship is big.", "The sheep is big."],
        ["I need a bat.", "I need a pet."],
        ["It is too thick.", "It is too sick."]
    ],
    "longas": [
        
        ["I legit have no idea where my keys are right now.",
            "I legit have no idea where my things are right now."],
        ["I don't have much to say right now, but I think I've said it all.",
            "I cannot stay here with you guys right now, but I'll be back later to see you all."],
        ["Are you sure you can hear me right or am I breaking up?",
            "Are you sure what you're saying is right or are you making this up?"],
        ["There's something I should have said a long time ago.",
            "There's something I should have done a long time ago."],
        ["There's no reason to panic whatsoever, so let's stay calm and wait.",
            "There's no reason now to go anywhere, so let's stay here and wait."],
        ["This is one of the most complicated things in the world, so you have to practice a lot.",
            "This is one of the simplest things in the world if you have practiced a lot."],
        ["I was going to say that, but you beat me to it.",
            "I was going to do that, but you beat me to it."],

        ["The author of that book is someone I really admire.",
            "The other author of that book is someone I really admire."],

        ["How exactly do you think it's going to work?",
            "How exactly do you think we're going to make it work?"],

        ["The thunderstorm lasted for several hours last night.",
            "The snowstorms lasted for several hours last night."],

        ["I can't believe it's already been twelve years since we met.",
            "I can't believe it's already been twenty years since we met."],

        ["She was born on the thirteenth of March, in the year nineteen ninety-three.",
            "She was born on the thirtieth of March, in the year nineteen ninety-three."],

        ["He finished in third place, just behind the athlete from Australia.",
            "He finished in first place, just behind the athlete from Australia."],

        ["I don't know what they were thinking, but they completely ruined the entire franchise.",
            "I don't know what they were thinking, but they almost managed to ruin the entire franchise."],

        ["The eighty participants were divided into eight different teams for the competition.",
            "The eighteen participants were divided into eight different teams for the competition."],

        ["He scored ninety points in the test, which was the highest score in the class.",
            "He scored nineteen points in the test, which was the highest score in the class."],
        
        ["I usually wake up at seven thirty on weekdays because I need time to get ready for work.", 
        "I usually wake up at six thirty on weekdays because I need time to get ready for work."],

        ["The meeting was scheduled for Thursday afternoon after everyone confirmed their availability.", 
        "The meeting was scheduled for Tuesday afternoon after everyone confirmed their availability."],

        ["She spent nearly fifty dollars on groceries at the supermarket yesterday.", 
        "She spent nearly fifteen dollars on groceries at the supermarket yesterday."],

        ["He’s been working at the company for over ten years and knows the system very well.", 
        "He’s been working at the company for over two years and is still learning the system."],

        ["They decided to take the train instead of driving because traffic was really bad.", 
        "They decided to take the bus instead of driving because traffic was really bad."],

        ["I thought the movie was pretty good overall, even though it was a bit too long.", 
        "I thought the movie was pretty bad overall, even though it had a strong cast."],

        ["We ordered two large pizzas for dinner since everyone was pretty hungry.", 
        "We ordered four large pizzas for dinner since everyone was pretty hungry."],

        ["He said he would arrive around eight o’clock, but he warned us he might be late.", 
        "He said he would arrive around eight thirty, but he warned us he might be late."],

        ["She almost forgot to send the email before leaving the office for the day.", 
        "She completely forgot to send the email before leaving the office for the day."],

        ["The store closes at nine during the week, so we need to get there early.", 
        "The store closes at ten during the week, so we still have some time."],

        ["I’ve met her a couple of times at work during team meetings.", 
        "I’ve never met her in person at work, only through online meetings."],

        ["They were happy with the results at the end of the project after months of hard work.", 
        "They were disappointed with the results at the end of the project despite months of hard work."],

        ["I think everyone is entitled to their opinion as long as they keep it respectful.", 
        "I think everyone is entitled to their opinion, but some people are very disrespectful."],

        ["I thought you were coming earlier, but I guess plans changed.",
        "I thought you were coming later, but I guess plans changed."],

        ["He said he needed a few minutes to finish what he was doing.",
        "He said he needed a few hours to finish what he was doing."],

        ["She usually takes her time when making important decisions.",
        "She usually makes quick decisions when the situation is urgent."],

        ["I didn’t mean to interrupt you, but I needed to ask something.",
        "I didn’t want to bother you, but I needed to ask something."],

        ["We’ve been talking about this issue for weeks without reaching a decision.",
        "We’ve been thinking about this issue for weeks without reaching a decision."],

        ["He looked calm on the outside, even though he was nervous inside.",
        "He looked confident on the outside, even though he was nervous inside."],

        ["I’ll call you as soon as I arrive so you know I’m safe.",
        "I’ll text you as soon as I arrive so you know I’m safe."],

        ["She realized she had made a mistake as soon as it was too late.",
        "She realized she had made a mistake just in time to fix it."],

        ["We were supposed to meet at the entrance, not inside the building.",
        "We were supposed to meet inside the building, not at the entrance."],

        ["I can’t remember the last time I had a full day off.",
        "I can’t remember the last time I took a proper vacation."],

        ["He promised he would take care of everything while we were away.",
        "He promised he would look after everything while we were away."],

        ["The instructions were clear enough for everyone to follow.",
        "The instructions were confusing enough for everyone to ask questions."],

        ["She barely had time to eat before rushing out the door.",
        "She finally had time to eat before rushing out the door."],

        ["I assumed they already knew about the changes.",
        "I assumed they would eventually hear about the changes."],

        ["The room felt smaller once everyone sat down.",
        "The room felt quieter once everyone sat down."],

        ["He apologized for the delay and explained what had happened.",
        "He apologized for the confusion and explained what had happened."],

        ["We decided to postpone the trip because of the weather.",
        "We decided to cancel the trip because of the weather."],

        ["I was relieved to hear that no one was seriously hurt.",
        "I was shocked to hear that no one was seriously hurt."],

        ["She mentioned the problem briefly but didn’t go into details.",
        "She explained the problem carefully and went into details."],

        ["They agreed to meet again next week to finish the discussion.",
        "They agreed to talk again next week to continue the discussion."],

        ["The knight rode his horse through the night to reach the castle before dawn.",
            "The knight rode his horse through the day to reach the castle before sunset."]
    ]
};
