// data.js
const allDataPools = {
    "palavras": [
        ["Ship", "Sheep"],
        ["Bat", "Beat"],
        ["Think", "Sink"],
        ["Heart", "Hard"],
        ["Thick", "Sick"],
        ["Beach", "Bead"],
        ["Bed", "Bead"],
        ["Path", "Bath"],
        ["Path", "Past"],
        ["Path", "Patch"],
        ["Teeth", "Tease"],
        ["Cloth", "Clod"],
        ["Breath", "Bread"],
        ["Earth", "Earn"],
        ["Month", "Mund"],
        ["Worth", "Word"],
        ["North", "Nod"],
        ["School", "Skull"],
        ["Healthy", "Help"],
        ["Author", "Other"],
        ["Thunder", "Under"],
        ["Twelve", "Twenty"],
        ["Twelve", "Twelfth"],
        ["Twenty", "Twentieth"],
        ["Thirty", "Dirty"],
        ["Thirty", "Third"],
        ["Thirty", "Thirtieth"],
        ["Thirteen", "Thirteenth"],
        ["Thirteenth", "Thirtieth"],
        ["Thirty", "Thirteenth"],
        ["Third", "Thirst"],
        ["Thirty", "Thirsty"],
        ["Thirty", "Thirteen"],
        ["Forty", "Dirty"],
        ["Forty", "Fort"],        
        ["Four", "Fort"],        
        ["Forty", "Fourth"],
        ["Forty", "Fortieth"],
        ["Fourteen", "Fortieth"],
        ["Forty", "Fourteen"],
        ["Fourteen", "Fourteenth"],
        ["Fourth", "Force"],
        ["Fifty", "Fifth"],
        ["Fifty", "Fiftieth"],
        ["Fifteen", "Fiftieth"],
        ["Fifty", "Fifteen"],
        ["Fifteen", "Fifteenth"],
        ["Sixty", "Sixth"],
        ["Sixty", "Sixtieth"],
        ["Sixteen", "Sixtieth"],
        ["Sixty", "Sixteen"],
        ["Sixteen", "Sixteenth"],
        ["Seventy", "Seventh"],
        ["Seventy", "Seventieth"],
        ["Seventeen", "Seventieth"],
        ["Seventy", "Seventeen"],
        ["Seventeen", "Seventeenth"],
        ["Eighty", "Eighth"],
        ["Eighty", "Eightieth"],
        ["Eighteen", "Eightieth"],
        ["Eighty", "Eighteen"],
        ["Eighteen", "Eighteenth"],
        ["Ninety", "Ninth"],
        ["Ninety", "Ninetieth"],
        ["Nineteen", "Ninetieth"],
        ["Ninety", "Nineteen"],
        ["Nineteen", "Nineteenth"],
        ["Nine", "Ninth"],
        ["Ten", "Tenth"],
        ["Tense", "Tenth"],
        ["Ten", "Teen"],
        ["Teeth", "Tenth"],
        ["Throne", "Frawn"],
        ["Draw", "Drought"],
        ["A", "E"],
        ["D", "G"],
        ["J", "G"],
        ["K", "Key"],
        ["Key", "Q"],
        ["K", "Q"],
        ["S", "Z"],
        ["C", "Z"],
        ["Air", "R"],
        ["E", "I"],
        ["A", "I"],
        ["U", "Y"],
        ["I", "Y"],
        ["H", "8"],
        ["Good", "God"],
        ["Like", "Lick"],
        ["Month", "Mouth"],
        ["Strip", "Stripe"],
        ["Rat", "Hat"],
        ["Hip", "Rip"],
        ["Right", "White"],
        ["They", "Their"],
        ["It", "Its"],
        ["They", "Day"],
        ["Fair", "Fear"],
        ["Hear", "Rear"],
        ["Here", "Hare"],
        ["Rare", "Hare"],
        ["Fast", "Feast"],
        ["Best", "Beast"],
        ["Mad", "Made"],
        ["Heal", "Real"],
        ["Host", "Roast"],
        ["Hose", "House"],
        ["Hot", "Rot"],
        ["Beach", "Beat"],
        ["Bot", "Botch"],
        ["Let", "Latch"],
        ["Pet", "Patch"],
        ["Mat", "Mash"],
        ["Mutt", "Much"],
        ["Mat", "Match"],
        ["Hatch", "Hat"],
        ["Shore", "Chore"],
        ["Shoes", "Choose"],
        ["Choose", "Chose"],
        ["Fat", "Fetch"],
        ["Rit", "Rich"],
        ["Rit", "Hit"],
        ["Rich", "Reach"],
        ["Catch", "Cat"],
        ["Him", "Rim"],
        ["Pie", "Pea"],
        ["Flea", "Fly"],
        ["Here", "Hire"],
        ["Pine", "Pin"],        
        ["Fit", "Fight"],
        ["Fire", "Fear"],
        ["Hid", "Rid"],
        ["Rid", "Weed"],
        ["Fine", "Fin"],
        ["Pill", "Pile"],
        ["Deal", "Dial"],
        ["Tree", "Try"],
        ["Rail", "Real"],
        ["Beer", "Bear"],
        ["Bee", "By"],
        ["Bird", "Beard"],
        ["Full", "Fool"],
        ["Flour", "Floor"],
        ["Tree", "Three"],
        ["Thrust", "Trust"],
        ["Path", "Pat"],
        ["Though", "Tough"],
        ["Taught", "Thought"],
        ["Tough", "Thought"],
        ["Though", "Thought"],
        ["Fought", "Thought"],
        ["Three", "Free"],
        ["Then", "Ten"],
        ["Thus", "Fuss"],
        ["One", "Want"],
        ["Fate", "Faith"],
        ["Fit", "Fish"],
        ["Fist", "Fish"],
        ["Are", "Air"],
        ["Space", "Spice"],
        ["Simple", "Simply"],
        ["Clearly", "Clear"],
        ["Sure", "Surely"],
        ["Soon", "Son"],
        ["Sun", "Soon"],                
        ["World", "Word"],
        ["Win", "When"],
        ["Daughter", "Laughter"],
        ["Stop", "Spot"],
        ["Evening", "Even"],
        ["Eve", "Even"],
        ["Year", "Yearn"],
        ["Waste", "West"],
        ["Easy", "Ease"],
        ["Loosen", "Loose"],
        ["Lose", "Lousy"],
        ["Lost", "Last"],
        ["Sorely", "Surely"],    
        ["Sorry", "Sorely"],
        ["Sorely", "Solely"],
        ["Within", "Without"],
        ["Without", "Withdraw"],
        ["Withhold", "Withdraw"],
        ["Withhold", "Without"],
        ["Sir", "Sure"],
        ["Sure", "Shore"],
        ["Sleep", "Split"],
        ["Sleep", "Slip"],
        ["Sleep", "Spill"],
        ["Spill", "Spell"],
        ["United", "Unity"],
        ["Unit", "Unity"],
        ["Unit", "United"],
        ["Met", "Meat"],
        ["Course", "Curse"],
        ["Curse", "Coarse"],
        ["Wild", "Wield"],
        ["Weld", "Wild"],
        ["Will", "Well"],
        ["Wine", "Win"],
        ["Wait", "White"],
        ["Wine", "Win"],
        ["Throne", "Drone"]
    ],
    "curtas": [
        ["I am here.", "I can't hear."],
        ["I can drive.", "I can dive."],
        ["He was home.", "We are home."],
        ["All of you.", "I love you."],
        ["Is it true?", "It is true."],
        ["How are you doing?", "What are you doing?"],
        ["They are people.", "There are people."],
        ["I love it.", "All of it."],
        ["Everybody's here.", "Everybody hears."],
        ["Can you see?", "Can't you see?"],
        ["They are people.", "There are people."],
        ["These are books", "They are books"],
        ["Are you ready?", "Are you reading?"],
        ["What did you say?", "Where did you stay?"],
        ["It's too cold.", "It isn't cold."],
        ["What did you say?", "What do you say?"],
        ["Why is that?", "What is that?"],
        ["This isn't right.", "This wasn't right."],
        ["Where are you going?", "When are you going?"],
        ["Is it clear?", "Is it near?"],
        ["That's not fair.", "That's not far."],
        ["It's close.", "It's closed."],
        ["Not too much.", "Not so much."],
        ["This is awesome.", "This is wholesome."],
        ["This is awful.", "This is awesome."],
        ["This is terrible.", "This is terrific."],
        ["This is great.", "This was great."],
        ["He's on the corner.", "He's in the corner."],
        ["I'm tired.", "I tried."],
        ["We're artists.", "Weird artists."],
        ["I have the keys.", "I have the case."],
        ["I miss you.", "I'm seeing you."],
        ["No idea.", "Not ideal."],
        ["I knew it.", "I'm new to it."],
        ["What do you say?", "Why do you stay?"],
        ["I read the book.", "The book is red."],
        ["I know you.", "I'm not you."],
        ["How do you do?", "What do you do?"],
        ["I know you.", "I'm not you."],
        ["I'm hearing things.", "I'm doing things."],
        ["I'm hearing them.", "I'm here with them."],
        ["I am sleepy.", "I am sleeping."],
        ["It seems right.", "It isn't right."],

        ["The ship is big.", "The sheep is big."],
        ["I need a bat.", "I need a pet."],
        ["It is too thick.", "It is too sick."]
    ],
    "longas": [
        
        ["I legit have no idea where my keys are right now.",
            "I legit have no idea where my things are right now."],
        ["I don't have much to say right now, but I think I've said it all.",
            "I cannot stay here with you guys right now, but I'll be back later to see you all."],
        ["Are you sure you can hear me right or am I breaking up?",
            "Are you sure what you're saying is right or are you making this up?"],
        ["There's something I should have said a long time ago.",
            "There's something I should have done a long time ago."],
        ["There's no reason to panic whatsoever, so let's stay calm and wait.",
            "There's no reason now to go anywhere, so let's stay here and wait."],
        ["This is one of the most complicated things in the world, so you have to practice a lot.",
            "This is one of the simplest things in the world if you have practiced a lot."],
        ["I was going to say that, but you beat me to it.",
            "I was going to do that, but you beat me to it."],

        ["The author of that book is someone I really admire.",
            "The other author of that book is someone I really admire."],

        ["How exactly do you think it's going to work?",
            "How exactly do you think we're going to make it work?"],

        ["The thunderstorm lasted for several hours last night.",
            "The snowstorms lasted for several hours last night."],

        ["I can't believe it's already been twelve years since we met.",
            "I can't believe it's already been twenty years since we met."],

        ["She was born on the thirteenth of March, in the year nineteen ninety-three.",
            "She was born on the thirtieth of March, in the year nineteen ninety-three."],

        ["He finished in third place, just behind the athlete from Australia.",
            "He finished in first place, just behind the athlete from Australia."],

        ["I don't know what they were thinking, but they completely ruined the entire franchise.",
            "I don't know what they were thinking, but they almost managed to ruin the entire franchise."],

        ["The eighty participants were divided into eight different teams for the competition.",
            "The eighteen participants were divided into eight different teams for the competition."],

        ["He scored ninety points in the test, which was the highest score in the class.",
            "He scored nineteen points in the test, which was the highest score in the class."],
        
        ["I usually wake up at seven thirty on weekdays because I need time to get ready for work.", 
        "I usually wake up at six thirty on weekdays because I need time to get ready for work."],

        ["The meeting was scheduled for Thursday afternoon after everyone confirmed their availability.", 
        "The meeting was scheduled for Tuesday afternoon after everyone confirmed their availability."],

        ["She spent nearly fifty dollars on groceries at the supermarket yesterday.", 
        "She spent nearly fifteen dollars on groceries at the supermarket yesterday."],

        ["He’s been working at the company for over ten years and knows the system very well.", 
        "He’s been working at the company for over two years and is still learning the system."],

        ["They decided to take the train instead of driving because traffic was really bad.", 
        "They decided to take the bus instead of driving because traffic was really bad."],

        ["I thought the movie was pretty good overall, even though it was a bit too long.", 
        "I thought the movie was pretty bad overall, even though it had a strong cast."],

        ["We ordered two large pizzas for dinner since everyone was pretty hungry.", 
        "We ordered four large pizzas for dinner since everyone was pretty hungry."],

        ["He said he would arrive around eight o’clock, but he warned us he might be late.", 
        "He said he would arrive around eight thirty, but he warned us he might be late."],

        ["She almost forgot to send the email before leaving the office for the day.", 
        "She completely forgot to send the email before leaving the office for the day."],

        ["The store closes at nine during the week, so we need to get there early.", 
        "The store closes at ten during the week, so we still have some time."],

        ["I’ve met her a couple of times at work during team meetings.", 
        "I’ve never met her in person at work, only through online meetings."],

        ["They were happy with the results at the end of the project after months of hard work.", 
        "They were disappointed with the results at the end of the project despite months of hard work."],

        ["I think everyone is entitled to their opinion as long as they keep it respectful.", 
        "I think everyone is entitled to their opinion, but some people are very disrespectful."],

        ["The knight rode his horse through the night to reach the castle before dawn.",
            "The knight rode his horse through the day to reach the castle before sunset."]
    ]
};
